server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/yourusername/acsp-config.git}
          default-label: ${CONFIG_GIT_BRANCH:main}
          search-paths: '{application}'
          clone-on-start: true
          timeout: 5
          force-pull: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
