server:
  port: 8085

spring:
  application:
    name: ai-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      model: ${OPENAI_MODEL:gpt-4}
      temperature: ${OPENAI_TEMPERATURE:0.7}
      max-tokens: ${OPENAI_MAX_TOKENS:2000}
    azure:
      openai:
        api-key: ${AZURE_OPENAI_API_KEY:}
        endpoint: ${AZURE_OPENAI_ENDPOINT:}
    anthropic:
      api-key: ${ANTHROPIC_API_KEY:}
      model: ${ANTHROPIC_MODEL:claude-2}
    vertex:
      project-id: ${VERTEX_PROJECT_ID:}
      location: ${VERTEX_LOCATION:us-central1}
      credentials-path: ${VERTEX_CREDENTIALS_PATH:}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  ratelimiter:
    instances:
      ai:
        limitForPeriod: 50
        limitRefreshPeriod: 1m
        timeoutDuration: 10s
  retry:
    instances:
      ai:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2

logging:
  level:
    com.acsp: DEBUG
    org.springframework: INFO
    org.springframework.ai: INFO
