# Build stage
FROM node:18-alpine AS build
WORKDIR /app
COPY ./frontend/package*.json ./
RUN npm ci
COPY ./frontend .
RUN npm run build

# Run stage
FROM nginx:alpine
COPY --from=build /app/dist/acsp /usr/share/nginx/html
COPY ./deployment/docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
