apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acsp

resources:
  - namespace.yaml
  - gateway.yaml
  - config-server.yaml
  - auth-service.yaml
  - tenant-service.yaml
  - ticket-service.yaml
  - notification-service.yaml
  - ai-service.yaml
  - kb-service.yaml
  - chat-service.yaml
  - search-service.yaml
  - analytics-service.yaml
  - observability-service.yaml

commonLabels:
  app.kubernetes.io/part-of: acsp
  app.kubernetes.io/managed-by: kustomize
